declare const worker: Worker;
declare const renderSettings: HTMLElement;
declare const widthInput: HTMLInputElement;
declare const heightInput: HTMLInputElement;
declare const raysPerPixel: HTMLInputElement;
declare const samplesLabel: HTMLSpanElement;
declare const radioButtons: NodeListOf<HTMLInputElement>;
declare const renderButton: HTMLButtonElement;
declare const renderTime: HTMLSpanElement;
declare const canvas: HTMLCanvasElement;
declare const ctx: CanvasRenderingContext2D;
declare let sceneType: string;
declare let width: number;
declare let height: number;
declare let numberOfSamples: number;
declare let t0: number;
declare let t1: number;
declare let preventRenderRequests: boolean;
//# sourceMappingURL=main.d.ts.map